ratings:
  namespace: bank-bookinfo-dev
  image: ghcr.io/bankhubjar/bookinfo-ratings
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-dev-ratings-mongodb-secret
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  # host: bookinfo.dev.opsta.net
  # path: "/student108/ratings(/|$)(.*)"
  host: bookinfo.dev.hellodolphin.in.th
  path: "/bank(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-dev-ratings-mongodb:27017/?authSource=ratings
  MONGO_DB_NAME: ratings-dev
  MONGO_DB_USERNAME: ratings-dev
  COMMIT_Id: CHANGEME