apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bookinfo-ratings-bank
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: hellodolphin.in.th
      http:
        paths:
        - path: /bank(/|$)(.*)
          pathType: Prefix
          backend:
            serviceName: {{ .Release.Name }}
            servicePort: {{ .Values.ratings.port }}

